### ISSUE TITLE
新）Docker

### ISSUE THREAD

**Issue by sharin-sushi** [sharin-sushi/V-Kara-Lists#62]

**Comment by sharin-sushi** [comment]
docker構成完成。
（全てdocker内で起動し、ブラウザからアプリを動かすことができた。）
ところどころ不審点あるが、dockerの構築のせいか不明。

- db起動が終わる前にapiが起動してしまい、アクセスできずapiが落ちる。
Docker DeskTop でdb起動後にapiを起動すればエラーは発生しない。
なお、docker-compose.ymlにてdepends_onは記述している。
これについては、depens先の準備が完全に終わるのを待つわけじゃない様子。
```
depends_on:
    - "db"
```

- docker-compose build前にnpm run buildして.next/BUILD_IDを作成しておく必要がある。
docker上でnpm run buildして生成したBUILD_IDでは
```Error: ENOENT: no such file or directory, open '/app/src/.next/BUILD_ID'```
となる。

- docker内でdb, api, appを起動すると、500エラーとなる。
appをVSCode上でnpm run devまたはbuild/startした場合にはこのエラーは発生しない。
```| domain.backendHost: http://localhost:8080
0016go_next_relation-app-1  | axios.getでerroe: AxiosError: connect ECONNREFUSED 127.0.0.1:8080
  at AxiosError.from (file:///app/src/node_modules/axios/lib/core/AxiosError.js:89:14)
  at RedirectableRequest.handleRequestError (file:///app/src/node_modules/axios/lib/adapters/http.js:606:25)
  at RedirectableRequest.emit (node:events:517:28)
  at eventHandlers.<computed> (/app/src/node_modules/follow-redirects/index.js:14:24)
  at ClientRequest.emit (node:events:517:28)
  at Socket.socketErrorListener (node:_http_client:501:9)
  at Socket.emit (node:events:517:28)
  at emitErrorNT (node:internal/streams/destroy:151:8)
  at emitErrorCloseNT (node:internal/streams/destroy:116:3)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
port: 8080,
address: '127.0.0.1',
syscall: 'connect',
code: 'ECONNREFUSED',
errno: -111,
config: {
  transitional: {
       silentJSONParsing: true,
       forcedJSONParsing: true,
      clarifyTimeoutError: false```

**Comment by sharin-sushi** [comment]
一通りの起動確認はできたため終了。
既コメントのエラーが再発したら再始動。

**Comment by sharin-sushi** [comment]
トラブル 1. について解決案

- Docker公式の日本語訳[healthcheck](https://docs.docker.jp/engine/reference/builder.html#healthcheck)
- 使用例
  - はてなブログ[docker-composeでMySQLの起動を待つ](https://blog.mtb-production.info/entry/2021/09/18/204107)
  - GitHub bxcodec/go-clean-archの[compose.yaml](https://github.com/bxcodec/go-clean-arch/blob/master/compose.yaml)

**Comment by sharin-sushi** [comment]
- トラブル発生
  - api構築完了し、動作確認したところ以下トラブルが発生した。
    - dockerコンテナ内で3つとも起動し安定するものの、apiとappの接続が上手くいかない。これはブラウザでappを操作しリクエストを送った際も、Poasmanからリクエストを送った際もエラーとなった。
    
Postman
```
GET http://localhost:8080/v1/vcontents/
Error: connect ECONNREFUSED 127.0.0.1:8080

PUT http://localhost:8080/v1/users/login
Error: connect ECONNREFUSED 127.0.0.1:8080
```

ブラウザapp(localhost:80)から
```
PUT http://localhost:8080/login
net::ERR_CONNECTION_REFUSED
```

ブラウザで直接api(localhost:8080)へ接続
```
localhost で接続が拒否されました。
ERR_CONNECTION_REFUSED
```

また、dbをdockerで、apiとappをVSCodeで立ち上げた際は、問題なく機能した。


よって、Dockerの設定ミスと思われるが、原因不明である。

**Comment by sharin-sushi** [comment]
追加情報

Dockerでapiを起動し8080のポートを使用しているにも関わらず、VSCodeでも8080でapiを起動できる。
